import {
  isIOS,
  isAndroid,
  ScreenWidth,
  ScreenHeight,
  ScreenScale,
  ScreenFontScale,
  WindowWidth,
  WindowHeight,
  WindowScale,
  WindowFontScale,
  PlatformVersion,
} from "./helpers/device/DeviceInfo";

import {
  isIPhoneNotchFamily,
  isIPhoneXFamily,
  hasNotch,
  isIPhoneX,
  isIPhoneXr,
  isIPhoneXs,
  isIPhoneSE,
  isIPhoneXsMax,
  getStatusBarHeight,
  isIPhone11,
  isIPhone11Pro,
  isIPhone11ProMax,
  isIPhone12,
  isIPhone12Pro,
  isIPhone12ProMax,
  isIPhone12Mini,
} from "./helpers/notch/Notch";
import normalizeText from "./helpers/normalize/normalizeText";

import { numberFormat } from "./helpers/text/Text";

export {
  isIOS,
  isAndroid,
  ScreenWidth,
  ScreenHeight,
  ScreenScale,
  ScreenFontScale,
  WindowWidth,
  WindowHeight,
  WindowScale,
  WindowFontScale,
  PlatformVersion,
  getStatusBarHeight,
  hasNotch,
  isIPhoneNotchFamily,
  isIPhoneXFamily,
  isIPhoneSE,
  isIPhoneX,
  isIPhoneXr,
  isIPhoneXs,
  isIPhoneXsMax,
  isIPhone11,
  isIPhone11Pro,
  isIPhone11ProMax,
  isIPhone12,
  isIPhone12Pro,
  isIPhone12ProMax,
  isIPhone12Mini,
  numberFormat,
  normalizeText,
};
